version: "3.9"

services:
  strapi:
    container_name: strapi
    build:
      context: .
    restart: unless-stopped
    networks:
      - strapidb
    ports:
      - "1337:1337"
    depends_on:
      - strapiDB
    volumes:
      - /opt/app/strapi/node_modules
      - ./strapi/:/opt/app/strapi
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - "5432:5432"
    networks:
      - strapidb
networks:
  strapidb:
    name: strapidb
    driver: bridge
volumes:
  strapi-data:

